### ISSUE TITLE
gitbashで動作が止まる不具合

### ISSUE THREAD

**Issue by ArakiTakaki** [takumus/tslib-cli#1]
## 概要

環境

- gitbash
- Node10系12系共に落ちる

![asdf](https://user-images.githubusercontent.com/29527889/77824224-7f8ec800-7144-11ea-90a1-7e1479ae50fa.PNG)

おそらくreadlineSyncが悪さをしていると思います。
どうにかならないものでしょうか？

**Comment by takumus** [comment]
ありがとうございます。こちらでも確認しました。
おっしゃる通り`readline-sync`が相性が悪いみたいですね！
`readline`を使うように修正しました。
